
types:
  'note':
    emoji: "✍️"
    template: '{_id:dot:>3} {title:<14}     {body:body:nn:orange}'
    fields:
      - name: title
        width: 0
        values: text
        required: true

      - name: date
        width: false
        values: text
        required: true

      # note: body has 'values: markdown'

  'task':
    emoji: "✅"
    template: '{_id:dot:>3} {title:<57} : {project:>4:project} {label:<7:label}  {due_date} {body:body:nn:orange}'
    fields:
      - name: title
        width: 0
        values: any
        required: true 

      - name: project
        width: 40
        values:
          'library': 'cornflowerblue'
          'cli': 'red'
          'pwa': 'burlywood'
          'server': 'red'
          'cloud': 'green'
        required: false 

      - name: label
        width: 90
        values:
          'feat': 'teal'
          'bug': 'crimson'
          'refactor': 'dodgerblue'
        required: false 

      - name: due_date
        width: 130
        values: date
        required: false 
  
order:
  - task
  - note

formatters:
  dot: '={v}.'
  nn: "?\n{v}"
  project:
    'library': 'red'
    'cli': 'purple'
    'pwa': 'blue'
    'server': 'white'
    'cloud': 'cyan'
  label:
    'bug': 'red'
    'feat': 'green'
    'refactor': 'blue'
