formatters:
  dot: ={v}.
  label:
    bug: red
    feat: green
    refactor: blue
  nn: '?

    {v}'
  project:
    cli: purple
    cloud: cyan
    library: red
    pwa: blue
    server: white
order:
- to-dodo
- note
types:
  note:
    emoji: "\u270D\uFE0F"
    fields:
    - name: title
      required: true
      values: text
      width: 0
    - name: date
      required: true
      values: text
      width: false
    template: '{_id:dot:>3} {title:<14}     {body:body:nn:orange}'
  to-dodo:
    emoji: "\U0001F680"
    fields:
    - name: title
      required: true
      values: any
      width: 0
    - name: project
      required: false
      values:
        cli: red
        cloud: green
        library: cornflowerblue
        pwa: burlywood
        server: red
      width: 40
    - name: label
      required: false
      values:
        bug: crimson
        feat: teal
        refactor: dodgerblue
      width: 90
    - name: due_date
      required: false
      values: date
      width: 130
    template: '{_id:dot:>3} {title:<57} : {project:>4:project} {label:<7:label}  {due_date}
      {body:body:nn:orange}'
