version: "3.9"
services:
  app:
    image: ssurrealism/tangler-app
    volumes:
      - ./app-web:/app
  srv:
    image: ssurrealism/tangler-server
    volumes:
      - ./app/:/usr/src/app
  proxy:
    # image: ssurrealism/tangler-proxy
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
