version: "3.9"
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 5173:5173
  srv:
    build: .
    ports:
      - 8000:8000
  proxy:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
