version: "3.9"
services:
  app:
    # image: ssurrealism/tangler-app
    build: ./app
    volumes:
      - ./app:/app
  srv:
    # image: ssurrealism/tangler-server
    build: .
  proxy:
    # image: ssurrealism/tangler-proxy
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
