apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.component: frontend
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.component: frontend
  template:
    metadata:
      labels:
        app.component: frontend
    spec:
      containers:
        - image: ssurrealism/tangler-app
          name: app
          ports:
            - name: http
              containerPort: 5173
