apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app.component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.component: proxy
  template:
    metadata:
      labels:
        app.component: proxy
    spec:
      containers:
        - image: ssurrealism/tangler-proxy
          name: proxy
          ports:
            - containerPort: 80
